name: tastysetup
app_id: da_KwGIWtMUmbWo
owner: elalaoui
package: .
capabilities:
  instaboot:
    mode: null
    requests:
    - path: /
  database:
    engine: mysql
debug: true
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0
