kind: wasmer.io/App.v0
name: tastysetup
owner: elalaoui
package: .
capabilities:
  instaboot:
    mode: null
    requests:
    - path: /
  database:
    engine: mysql
debug: true
scaling:
  mode: single_concurrency
app_id: da_KwGIWtMUmbWo
