[package]
name = "elalaoui/tastysetup"
version = "0.1.0"
description = "TastyIgniter restaurant ordering system on Wasmer Edge"
license = "MIT"

[dependencies]
"php/php" = "=8.3.4"

[fs]
"/app" = "."
"/app/public" = "public"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app/public", "-S", "localhost:8080"]
